#!/bin/bash -exu

ROOT=${PWD}

function download_terraform() {
  local platform
  local zip_name

  platform=${1}
  arch=${2}
  zip_name="terraform_${TF_VERSION}_${platform}_${arch}.zip"

  ZIP_URL="${URL_BASE}/${TF_VERSION}/${zip_name}"
  wget ${ZIP_URL} -q
  unzip -o ${zip_name}

  rm -rf ${zip_name}
}

pushd ${ROOT}/terraform-binaries > /dev/null
  for platform in "darwin" "linux"; do
    for arch in "amd64" "arm64"; do
      download_terraform ${platform} ${arch}
      mv terraform "terraform_${platform}_${arch}"
    done
  done
  for platform in "windows"; do
    for arch in "amd64"; do
      download_terraform ${platform} ${arch}
      mv terraform.exe "terraform_${platform}_${arch}.exe"
    done
  done
popd > /dev/null
