#!/bin/bash -exu

ROOT="${PWD}"

function main() {
  local source_file
  source_file="${ROOT}/source-file/bosh-source.json"

  pushd "${ROOT}/bbl-states/${BBL_STATE_DIR}" > /dev/null
    export YTT_TARGET="$(bbl director-address)"
    export YTT_CLIENT="$(bbl director-username)"
    export YTT_CLIENT_SECRET="$(bbl director-password)"
    export YTT_CA_CERT="$(bbl director-ca-cert)"
    export YTT_JUMPBOX_URL="$(bbl jumpbox-address)"
    export YTT_JUMPBOX_SSH_KEY="$(bbl ssh-key)"
  popd > /dev/null

  ytt -f "${ROOT}/bbl-ci/ci/tasks/create-bosh-deployment-source-file/source-template.yml" --data-values-env YTT > "${source_file}"
}

main
