---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/bbl-deployment

inputs:
- name: bbl-ci
- name: bbl-states

outputs:
- name: source-file

params:
  BBL_STATE_DIR:

run:
  path: bbl-ci/ci/tasks/create-bosh-deployment-source-file/task
