// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"
)

type Zone struct {
	RetrieveStub        func(region string) ([]string, error)
	retrieveMutex       sync.RWMutex
	retrieveArgsForCall []struct {
		region string
	}
	retrieveReturns struct {
		result1 []string
		result2 error
	}
	retrieveReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Zone) Retrieve(region string) ([]string, error) {
	fake.retrieveMutex.Lock()
	ret, specificReturn := fake.retrieveReturnsOnCall[len(fake.retrieveArgsForCall)]
	fake.retrieveArgsForCall = append(fake.retrieveArgsForCall, struct {
		region string
	}{region})
	fake.recordInvocation("Retrieve", []interface{}{region})
	fake.retrieveMutex.Unlock()
	if fake.RetrieveStub != nil {
		return fake.RetrieveStub(region)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.retrieveReturns.result1, fake.retrieveReturns.result2
}

func (fake *Zone) RetrieveCallCount() int {
	fake.retrieveMutex.RLock()
	defer fake.retrieveMutex.RUnlock()
	return len(fake.retrieveArgsForCall)
}

func (fake *Zone) RetrieveArgsForCall(i int) string {
	fake.retrieveMutex.RLock()
	defer fake.retrieveMutex.RUnlock()
	return fake.retrieveArgsForCall[i].region
}

func (fake *Zone) RetrieveReturns(result1 []string, result2 error) {
	fake.RetrieveStub = nil
	fake.retrieveReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *Zone) RetrieveReturnsOnCall(i int, result1 []string, result2 error) {
	fake.RetrieveStub = nil
	if fake.retrieveReturnsOnCall == nil {
		fake.retrieveReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.retrieveReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *Zone) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.retrieveMutex.RLock()
	defer fake.retrieveMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Zone) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
