#!/usr/bin/env bash

set -e -x -u

root="${PWD}"
version=$(cat "${root}/bbl-release/version")

shaOS=$(shasum -a 256 bbl-release/bbl-*_osx | cut -d ' ' -f 1)
shaLinux=$(shasum -a 256 bbl-release/bbl-*_linux_x86-64 | cut -d ' ' -f 1)

pushd homebrew-tap
  cat <<EOF > bbl.rb
class Bbl < Formula
  desc "Command line utility for standing up a BOSH director on an IAAS of your choice."
  homepage "https://github.com/cloudfoundry/bosh-bootloader"
  version "v${version}"

  if OS.mac?
    url "https://github.com/cloudfoundry/bosh-bootloader/releases/download/#{version}/bbl-#{version}_osx"
    sha256 "${shaOS}"
  elsif OS.linux?
    url "https://github.com/cloudfoundry/bosh-bootloader/releases/download/#{version}/bbl-#{version}_linux_x86-64"
    sha256 "${shaLinux}"
  end

  depends_on :arch => :x86_64
  depends_on "terraform" => "0.11.0"
  depends_on "cloudfoundry/tap/bosh-cli" => "2.0.48"

  def install
    binary_name = "bbl"
    if OS.mac?
      bin.install "bbl-#{version}_osx" => binary_name
    elsif OS.linux?
      bin.install "bbl-#{version}_linux_x86-64" => binary_name
    end
  end

  test do
    system "#{bin}/#{binary_name} --help"
  end
end
EOF

  cat bbl.rb

  git add bbl.rb
  if ! [ -z "$(git status --porcelain)" ];
  then
    git config --global user.email "cf-infrastructure@pivotal.io"
    git config --global user.name "CF Infrastructure"
    git commit -m "Release bbl ${version}"
  else
    echo "No new version to commit"
  fi
popd

cp -R homebrew-tap updated-brew-tap
