#!/usr/bin/env bash

set -e -x -u

root="${PWD}"
version=$(cat "${root}/bbl-release/version")

shaOSAmd64=$(shasum -a 256 bbl-release/bbl-*_osx_amd64 | cut -d ' ' -f 1)
shaOSArm64=$(shasum -a 256 bbl-release/bbl-*_osx_arm64 | cut -d ' ' -f 1)
shaLinuxAmd64=$(shasum -a 256 bbl-release/bbl-*_linux_amd64 | cut -d ' ' -f 1)
shaLinuxArm64=$(shasum -a 256 bbl-release/bbl-*_linux_arm64 | cut -d ' ' -f 1)

pushd homebrew-tap
  cat <<EOF > bbl.rb
class Bbl < Formula
  desc "Command line utility for standing up a BOSH director on an IAAS of your choice."
  homepage "https://github.com/cloudfoundry/bosh-bootloader"
  version "v${version}"

  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/cloudfoundry/bosh-bootloader/releases/download/#{version}/bbl-#{version}_osx_arm64"
      sha256 "${shaOSArm64}"
    else
      url "https://github.com/cloudfoundry/bosh-bootloader/releases/download/#{version}/bbl-#{version}_osx_amd64"
      sha256 "${shaOSAmd64}"
    end
  elsif OS.linux?
    if Hardware::CPU.arm?
      url "https://github.com/cloudfoundry/bosh-bootloader/releases/download/#{version}/bbl-#{version}_linux_arm64"
      sha256 "${shaLinuxArm64}"
    else
      url "https://github.com/cloudfoundry/bosh-bootloader/releases/download/#{version}/bbl-#{version}_linux_amd64"
      sha256 "${shaLinuxAmd64}"
    end
  end

  def install
    binary_name = "bbl"
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "bbl-#{version}_osx_arm64" => binary_name
      else
        bin.install "bbl-#{version}_osx_amd64" => binary_name
      end
    elsif OS.linux?
      if Hardware::CPU.arm?
        bin.install "bbl-#{version}_linux_arm64" => binary_name
      else
        bin.install "bbl-#{version}_linux_amd64" => binary_name
      end
    end
  end

  test do
    system "#{bin}/bbl", "--help"
  end
end
EOF

  cat bbl.rb

  git add bbl.rb
  if ! [ -z "$(git status --porcelain)" ];
  then
    git config --global user.email "cf-bosh-eng@pivotal.io"
    git config --global user.name "BOSH CI"
    git commit -m "Release bbl ${version}"
  else
    echo "No new version to commit"
  fi
popd

cp -R homebrew-tap updated-brew-tap
