#!/bin/bash -eu

function main() {
  local packages
  packages=${@}

	local root_dir
	root_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

  if [ -z "${packages}" ]; then
    echo "Usage: ./scripts/acceptance_tests packages...
Example: ./scripts/acceptance_tests bbl gcp"
    return
  fi

  local parallelFlag
  if [ "${BBL_IAAS}" == "aws" ]; then
    parallelFlag=""
  else
    parallelFlag="-p"
  fi

	pushd "${root_dir}/acceptance-tests" > /dev/null
      ginkgo -r -v ${parallelFlag} -race -failFast -randomizeAllSpecs -randomizeSuites ${packages}
	popd > /dev/null
}

main "${@:-""}"
