#!/bin/bash -eu

function main() {
  local iaas
  iaas=${1}

	local root_dir
	root_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

  if [ -z ${iaas} ]; then
    echo "Specify iaas: aws, gcp"
    return
  fi

	pushd "${root_dir}" > /dev/null
      ginkgo -r -race -failFast -randomizeAllSpecs -randomizeSuites acceptance-tests/bbl acceptance-tests/${iaas}
	popd > /dev/null
}

main "${@:-""}"
