#!/bin/bash -exu

GOBUILDTAGS="${GOBUILDTAGS:-""}"
packr2 install -tags="${GOBUILDTAGS}" -ldflags="-X main.Version=$(git rev-parse --short=7 HEAD)" github.com/cloudfoundry/bosh-bootloader/bbl
bbl "${@:-"-v"}"
