#!/usr/bin/env bash
set -eu -o pipefail

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

(
  cd "${ROOT_DIR}"
  if ! command -v golangci-lint &> /dev/null; then
    go install -v github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  fi
  golangci-lint run --enable goimports ./...
)
