#!/bin/bash -eux

ROOT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

function main {
  pushd "${ROOT_DIRECTORY}"
    docker pull cfinfrastructure/deployment

    docker run \
      -e AWS_REGION="${AWS_REGION}" \
      -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
      -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
      -e GCP_PROJECT_ID="${GCP_PROJECT_ID}" \
      -e GCP_REGION="${GCP_REGION}" \
      -e GCP_SERVICE_ACCOUNT_KEY="${GCP_SERVICE_ACCOUNT_KEY}" \
      -e GCP_ZONE="${GCP_ZONE}" \
      -e STATE_DIR="/tmp/state" \
      -v ${PWD}:/bosh-bootloader \
      -v ${CIPATH:-"${GOPATH}/src/github.com/cloudfoundry/infrastructure-ci"}:/ci \
      -v ${STATE_DIR}:/tmp/state \
      cfinfrastructure/deployment ${TEST_TASK:-"/ci/scripts/bosh-bootloader/concourse-integration/task"}
  popd
}

main
