#!/bin/bash -eu

ROOT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

pushd "${ROOT_DIRECTORY}"
  set -e
  docker pull cfinfrastructure/golang
  docker run -v $PWD:/bosh-bootloader \
    -v ${MEGA_CI:-"${GOPATH}/src/github.com/cloudfoundry/mega-ci"}:/mega-ci \
    cfinfrastructure/golang ${TEST_TASK:-"/mega-ci/scripts/ci/bosh-bootloader/test"}
popd
