#!/bin/bash -eux

ROOT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

function main {
  local binary_dir
  binary_dir="/tmp/bbl-concourse/bin"
  mkdir -p "${binary_dir}/concourse-release"
  mkdir -p "${binary_dir}/garden-release"
  mkdir -p "${binary_dir}/stemcell"

  set +e
  wget -nc -O "${binary_dir}/concourse-release/release.tgz" "http://bosh.io/d/github.com/concourse/concourse"
  wget -nc -O "${binary_dir}/garden-release/release.tgz" "http://bosh.io/d/github.com/cloudfoundry/garden-runc-release"
  wget -nc -O "${binary_dir}/stemcell/stemcell.tgz" "https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-trusty-go_agent"

  local stemcell_version
  stemcell_version="$(curl -v http://bosh.io/api/v1/stemcells/bosh-google-kvm-ubuntu-trusty-go_agent\?all\=1 | jq -r '.[0].version')"
  echo -n "${stemcell_version}" > "${binary_dir}/stemcell/version"
  set -e

  pushd "${ROOT_DIRECTORY}" > /dev/null

    docker pull cfinfrastructure/deployment

    docker run \
      -e AWS_REGION="${AWS_REGION:-""}" \
      -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-""}" \
      -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-""}" \
      -e GCP_PROJECT_ID="${GCP_PROJECT_ID:-""}" \
      -e GCP_REGION="${GCP_REGION:-""}" \
      -e GCP_SERVICE_ACCOUNT_KEY="${GCP_SERVICE_ACCOUNT_KEY:-""}" \
      -e GCP_ZONE="${GCP_ZONE:-""}" \
      -e CONCOURSE_DEPLOYMENT_PATH="/concourse-deployment" \
      -e STATE_DIR="/tmp/state" \
      -v ${PWD}:/bosh-bootloader \
      -v ${CIPATH:-"${GOPATH}/src/github.com/cloudfoundry/infrastructure-ci"}:/ci \
      -v ${binary_dir}/concourse-release:/concourse-release \
      -v ${binary_dir}/garden-release:/garden-release \
      -v ${binary_dir}/stemcell:/stemcell \
      -v ${CONCOURSE_DEPLOYMENT_PATH:-${GOPATH}/src/github.com/evanfarrar/concourse-deployment}:/concourse-deployment \
      -v ${STATE_DIR:-${PWD}}:/bbl-integration-s3 \
      cfinfrastructure/deployment ${TEST_TASK:-"/ci/scripts/bosh-bootloader/concourse-integration/task"}
  popd > /dev/null
}

main
