#!/bin/bash -eu

ROOT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

pushd "${ROOT_DIRECTORY}"
  set -e
  docker pull cfinfrastructure/golang
  docker run -v $PWD:/bosh-bootloader \
    -v ${INFRASTRUCTURE_CI:-"${GOPATH}/src/github.com/cloudfoundry/infrastructure-ci"}:/infrastructure-ci \
    cfinfrastructure/golang ${TEST_TASK:-"/infrastructure-ci/scripts/ci/bosh-bootloader/test"}
popd
