#!/bin/bash -eux

ROOT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

function main {
  pushd "${ROOT_DIRECTORY}"
    docker pull cfinfrastructure/deployment

    docker run \
      -e BBL_AWS_REGION="${BBL_AWS_REGION}" \
      -e BBL_AWS_ACCESS_KEY_ID="${BBL_AWS_ACCESS_KEY_ID}" \
      -e BBL_AWS_SECRET_ACCESS_KEY="${BBL_AWS_SECRET_ACCESS_KEY}" \
      -v $PWD:/bosh-bootloader \
      -v ${INFRASTRUCTURE_CI:-"${GOPATH}/src/github.com/cloudfoundry/infrastructure-ci"}:/infrastructure-ci \
      cfinfrastructure/deployment ${TEST_TASK:-"/infrastructure-ci/scripts/ci/bosh-bootloader/aws_integration"}
  popd
}

main
