#!/bin/bash -exu

root_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd ${root_dir}/../terraform/binary_dist
  ln -sfv $(which terraform) /tmp/terraform
  go-bindata -tags '!includeTerraform' -debug -pkg binary_dist -mode 0740 -o dev_shim.go -prefix /tmp/ /tmp/terraform

  # l33t h4x so we can check in a version of this that works with a raw `go build` and system terraform
  sed -ibk 's|:= "/tmp/terraform"|, _ := exec.LookPath("terraform")|' dev_shim.go
  rm -f dev_shim.gobk
  goimports -w dev_shim.go
popd
