#!/bin/bash -eu

function main() {
	local root_dir
	root_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

	pushd "${root_dir}" > /dev/null
		GO15VENDOREXPERIMENT=1 ginkgo -p -r -race -randomizeAllSpecs -randomizeSuites -skipPackage integration-test ${@}
	popd > /dev/null
}

main "${@:-""}"
