#!/bin/bash -exu

if [ "${@}" == "aws" ]; then
  pushd terraform/aws
    go-bindata -pkg aws -o templates.go templates
  popd
fi

if [ "${@}" == "azure" ]; then
  pushd terraform/azure
    go-bindata -pkg azure -o templates.go templates
  popd
fi

if [ "${@}" == "gcp" ]; then
  pushd terraform/gcp
    go-bindata -pkg gcp -o templates.go templates
  popd
fi
