#!/bin/bash -exu

root_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "${@}" == "aws" ]; then
  pushd ${root_dir}/../terraform/aws
    go-bindata -pkg aws -mode 0740 -o templates.go templates
  popd
fi

if [ "${@}" == "azure" ]; then
  pushd ${root_dir}/../terraform/azure
    go-bindata -pkg azure -mode 0740 -o templates.go templates
  popd
fi

if [ "${@}" == "gcp" ]; then
  pushd ${root_dir}/../terraform/gcp
    go-bindata -pkg gcp -mode 0740 -o templates.go templates
  popd
fi

if [ "${@}" == "openstack" ]; then
  pushd ${root_dir}/../terraform/openstack
    go-bindata -pkg openstack -mode 0740 -o templates.go templates
  popd
fi
