#!/bin/bash -exu

root_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TF_VERSION='0.11.7'

download_terraform () {
  wget -qO- \
    "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_${1}.zip" \
    | tar -xvz
}

pushd ${root_dir}/../terraform/binary_dist
  for platform in "darwin_amd64" "linux_386" "linux_amd64"; do
    download_terraform ${platform}
    go-bindata -tags 'includeTerraform' -pkg binary_dist -mode 0740 -o tf_binary_dist_${platform}.go terraform
  done
  for platform in "windows_386" "windows_amd64"; do
    download_terraform ${platform}
    go-bindata -tags 'includeTerraform' -pkg binary_dist -mode 0740 -o tf_binary_dist_${platform}.go terraform.exe
  done
popd
