#!/bin/bash -exu

root_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TF_VERSION='0.11.7'
URL_BASE="https://releases.hashicorp.com/terraform/${TF_VERSION}"

download_terraform () {
  tmpfile=$(mktemp)
  ZIP_URL="${URL_BASE}/terraform_${TF_VERSION}_${1}.zip"
  wget ${ZIP_URL} -qO ${tmpfile}
  unzip -o ${tmpfile}
}

pushd ${root_dir}/../terraform/binary_dist
  echo ${URL_BASE} > tf_binaries_fetched_from.txt
  for platform in "darwin_amd64" "linux_386" "linux_amd64" "freebsd_386" "freebsd_amd64"; do
    download_terraform ${platform}
    go-bindata -tags 'includeTerraform' -pkg binary_dist -mode 0740 -o tf_binary_dist_${platform}.go terraform
  done
  for platform in "windows_386" "windows_amd64"; do
    download_terraform ${platform}
    go-bindata -tags 'includeTerraform' -pkg binary_dist -mode 0740 -o tf_binary_dist_${platform}.go terraform.exe
  done
popd
