#!/bin/bash -exu

ROOT="${PWD}"

mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
  ln -s "${ROOT}/bosh-bootloader"

  export TF_LOG=DEBUG
  export TF_LOG_PATH="${ROOT}/tf-logs.txt"
  export BOSH_LOG_LEVEL=debug
  export BOSH_LOG_PATH="${ROOT}/bosh-logs/bosh-logs.txt"
  export TERRAFORM_BINARY_PATH=${ROOT}/terraform-binaries/terraform_linux

  cp  "${TERRAFORM_BINARY_PATH}" ./bosh-bootloader/terraform/binary_dist/terraform

  ./bosh-bootloader/scripts/acceptance_tests ${BBL_TEST_PACKAGES}
popd > /dev/null
