#!/bin/bash -exu

ROOT="${PWD}"

function main() {
  mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

  pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
    ln -s "${ROOT}/bosh-bootloader"
    ./bosh-bootloader/scripts/test
  popd > /dev/null
}

main
