---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/bbl-deployment

inputs:
- name: bbl-ci
- name: bosh-bootloader

run:
  path: bbl-ci/ci/tasks/test-bosh-bootloader/task
