name: auto-accept-dependabot

on:
  pull_request_target:

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          config: .github/auto-merge.yml
          command: "squash and merge"
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
